name: Deploy iOS to App Center

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: macOS-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Ionic
        run: |
          npm install -g @ionic/cli

      - name: Install Application modules
        working-directory: ./app
        env:
          CI: true
        run: npm install

      - name: Build IOS App
        working-directory: ./app
        env:
          CI: ""
        run: |
           ionic capacitor build ios --prod

      - name: Switch XCode Version
        run: sudo xcode-select -s /Applications/Xcode_11.2.app

      - name: Cache Pods dependencies
        uses: actions/cache@v1
        with:
          path: ./app/ios/App/Pods
          key: ${{ runner.OS }}-pods-cache-${{ hashFiles('**/app/ios/App/Podfile.lock') }}
          restore-keys: |
            ${{ runner.OS }}-pods-cache-

